"""
Django settings for summer project.

Generated by 'django-admin startproject' using Django 2.0.dev20170502021905.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mue$uwuasb5d360a$4^p@t61^fl2uyz+tkgcq3z&2(n)5sk0bv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'tag.apps.TagConfig',
     'article.apps.ArticleConfig',
     'author.apps.AuthorConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'summer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'summer.context_processors.global_setting',
            ],
        },
    },
]

WSGI_APPLICATION = 'summer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cms',
        'USER': 'summer',
        'PASSWORD': 'summer',
        'HOST': '172.27.10.129',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

SUMMER_CONFIG = {
    'SITE_NAME': os.getenv('SITE_NAME', 'SUMMER'),
    'SITE_DESCRIPTION': os.getenv('SITE_DESCRIPTION', 'Shared Your knowledge'),
    'SITE_HOME_BACKGROUND': os.getenv('SITE_HOME_BACKGROUND', '/static/img/home-bg.jpg'),
    'SITE_ARTICLE_BACKGROUND': os.getenv('SITE_POST_BACKGROUND', '/static/img/article-bg.jpg'),
    'SITE_FORM_BACKGROUND': os.getenv('SITE_FORM_BACKGROUND', '/static/img/form-bg.jpg'),
    'SITE_ERROR_BACKGROUND': os.getenv('SITE_ERROR_BACKGROUND', '/static/img/error-bg.png'),
    'SITE_ZHIHU_URL': os.getenv('ZHIHU_URL', 'https://www.zhihu.com/'),
    'SITE_GITHUB_URL': os.getenv('GITHUB_URL', 'https://github.com/anyisalin')
}
                                                   
