# Generated by Django 2.0.dev20170502021905 on 2017-08-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('raw_content', models.TextField(blank=True)),
                ('background', models.CharField(max_length=500, null=True)),
                ('vote', models.IntegerField(default=0)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='tag.Tag')),
            ],
            options={
                'ordering': ('-pub_time',),
            },
        ),
    ]
