# Generated by Django 2.0.dev20170502021905 on 2017-09-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20170915_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='pub_time',
            new_name='pub_date',
        ),
    ]
